# Generated by Django 3.2.12 on 2022-12-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enkelvoudiginformatieobject",
            name="indicatie_gebruiksrecht",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
